AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'Rakefile'
  TargetRubyVersion: 2.4

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 300
